package ject.ja.text.inflection

import ject.ja.text.Form
import ject.ja.text.SubForm.*
import ject.ja.text.Transformation.*
import ject.ja.text.Transforms

object Iku {

  val inflections: Map[Form, Transform] =
    Map(
      // Plain
      NonPast.plain -> Transforms.identity,
      Past.plain -> Transforms(stemOf("く"), attach("った")),
      Te.plain -> Transforms(stemOf("く"), attach("って")),
      Conditional.plain -> Transforms(stemOf("く"), attach("ったら")),
      Provisional.plain -> Transforms(stemOf("く"), attach("けば")),
      Potential.plain -> Transforms(stemOf("く"), attach("ける")),
      Passive.plain -> Transforms(stemOf("く"), attach("かれる")),
      Causative.plain -> Transforms(stemOf("く"), attach("かせる", "かす")),
      CausativePassive.plain -> Transforms(stemOf("く"), attach("かせられる")),
      Volitional.plain -> Transforms(stemOf("く"), attach("こう")),
      Alternative.plain -> Transforms(stemOf("く"), attach("ったり")),
      Imperative.plain -> Transforms(stemOf("く"), attach("け")),
      Sou.plain -> Transforms(stemOf("く"), attach("きそう")),
      Tai.plain -> Transforms(stemOf("く"), attach("きたい")),
      Progressive.plain -> Transforms(stemOf("く"), attach("っている", "ってる")),
      Form.of(Progressive, Past) -> Transforms(stemOf("く"), attach("っていた", "ってた")),
      Form.of(Potential, Te) -> Transforms(stemOf("く"), attach("けて")),
      Form.of(Potential, Past) -> Transforms(stemOf("く"), attach("けた")),
      Form.of(Causative, Te) -> Transforms(stemOf("く"), attach("かせて")),
      Form.of(Causative, Past) -> Transforms(stemOf("く"), attach("かせた")),
      Form.of(Tai, Te) -> Transforms(stemOf("く"), attach("きたくて")),
      // Polite
      NonPast.polite -> Transforms(stemOf("く"), attach("きます")),
      Past.polite -> Transforms(stemOf("く"), attach("きました")),
      Te.polite -> Transforms(stemOf("く"), attach("きまして")),
      Conditional.polite -> Transforms(stemOf("く"), attach("きましたら")),
      Provisional.polite -> Transforms(stemOf("く"), attach("きますなら")),
      Potential.polite -> Transforms(stemOf("く"), attach("けます")),
      Passive.polite -> Transforms(stemOf("く"), attach("かれます")),
      Causative.polite -> Transforms(stemOf("く"), attach("かせます", "かします")),
      CausativePassive.polite -> Transforms(stemOf("く"), attach("かせられます")),
      Volitional.polite -> Transforms(stemOf("く"), attach("きましょう")),
      Alternative.polite -> Transforms(stemOf("く"), attach("きましたり")),
      Imperative.polite -> Transforms(stemOf("く"), attach("きなさい")),
      Progressive.polite -> Transforms(stemOf("く"), attach("っています", "ってます")),
      Form.of(Progressive, Past).polite -> Transforms(stemOf("く"), attach("っていました", "ってました")),
      Form.of(Potential, Te).polite -> Transforms(stemOf("く"), attach("けまして")),
      Form.of(Potential, Past).polite -> Transforms(stemOf("く"), attach("けました")),
      Form.of(Causative, Te).polite -> Transforms(stemOf("く"), attach("かせまして")),
      Form.of(Causative, Past).polite -> Transforms(stemOf("く"), attach("かせました")),
      // Negative
      NonPast.negative -> Transforms(stemOf("く"), attach("かない", "かぬ", "かず")),
      Past.negative -> Transforms(stemOf("く"), attach("かなかった")),
      Te.negative -> Transforms(stemOf("く"), attach("かなくて", "かないで")),
      Conditional.negative -> Transforms(stemOf("く"), attach("かなかったら")),
      Provisional.negative -> Transforms(stemOf("く"), attach("かなければ")),
      Potential.negative -> Transforms(stemOf("く"), attach("けない")),
      Passive.negative -> Transforms(stemOf("く"), attach("かれない")),
      Causative.negative -> Transforms(stemOf("く"), attach("かせない", "かさない")),
      CausativePassive.negative -> Transforms(stemOf("く"), attach("かせられない")),
      Volitional.negative -> Transforms(stemOf("く"), attach("くまい")),
      Alternative.negative -> Transforms(stemOf("く"), attach("かなかったり")),
      Imperative.negative -> Transforms(stemOf("く"), attach("くな")),
      Sou.negative -> Transforms(stemOf("く"), attach("かなそう")),
      Form.of(Potential, Sou).negative -> Transforms(stemOf("く"), attach("けなそう")),
      Tai.negative -> Transforms(stemOf("く"), attach("きたくない")),
      Progressive.negative -> Transforms(stemOf("く"), attach("っていない", "ってない")),
      Form.of(Progressive, Past).negative -> Transforms(stemOf("く"), attach("っていなかった", "ってなかった")),
      Form.of(Tai, Sou).negative -> Transforms(stemOf("く"), attach("きたくなさそう")),
      Form.of(Potential, Te).negative -> Transforms(stemOf("く"), attach("けなくて")),
      Form.of(Potential, Past).negative -> Transforms(stemOf("く"), attach("けなかった")),
      Form.of(Causative, Te).negative -> Transforms(stemOf("く"), attach("かせなくて")),
      Form.of(Causative, Past).negative -> Transforms(stemOf("く"), attach("かせなかった")),
      // Polite negative
      NonPast.polite.negative -> Transforms(stemOf("く"), attach("きません")),
      Past.polite.negative -> Transforms(stemOf("く"), attach("きませんでした")),
      Te.polite.negative -> Transforms(stemOf("く"), attach("きませんで")),
      Conditional.polite.negative -> Transforms(stemOf("く"), attach("きませんでしたら")),
      Provisional.polite.negative -> Transforms(stemOf("く"), attach("きませんなら")),
      Potential.polite.negative -> Transforms(stemOf("く"), attach("けません")),
      Passive.polite.negative -> Transforms(stemOf("く"), attach("かれません")),
      Causative.polite.negative -> Transforms(stemOf("く"), attach("かせません", "かしません")),
      CausativePassive.polite.negative -> Transforms(stemOf("く"), attach("かせられません")),
      Volitional.polite.negative -> Transforms(stemOf("く"), attach("きますまい")),
      Alternative.polite.negative -> Transforms(stemOf("く"), attach("きませんでしたり")),
      Imperative.polite.negative -> Transforms(stemOf("く"), attach("きなさるな")),
      Progressive.polite.negative -> Transforms(stemOf("く"), attach("っていません", "ってません")),
      Form.of(Progressive, Past).polite.negative -> Transforms(stemOf("く"), attach("っていませんでした", "ってませんでした")),
      Form.of(Potential, Te).polite.negative -> Transforms(stemOf("く"), attach("けませんでして")),
      Form.of(Potential, Past).polite.negative -> Transforms(stemOf("く"), attach("けませんでした")),
      Form.of(Causative, Te).polite.negative -> Transforms(stemOf("く"), attach("かせませんでして")),
      Form.of(Causative, Past).polite.negative -> Transforms(stemOf("く"), attach("かせませんでした"))
    )

  val deinflections: Map[Form, Transform] =
    Map(
      // Plain
      NonPast.plain -> Transforms(ensureSuffix("く")),
      Past.plain -> Transforms(detach("った"), attach("く")),
      Te.plain -> Transforms(detach("って"), attach("く")),
      Conditional.plain -> Transforms(detach("ったら"), attach("く")),
      Provisional.plain -> Transforms(detach("けば"), attach("く")),
      Potential.plain -> Transforms(detach("ける"), attach("く")),
      Passive.plain -> Transforms(detach("かれる"), attach("く")),
      Causative.plain -> Transforms(detach("かせる", "かす"), attach("く")),
      CausativePassive.plain -> Transforms(detach("かせられる"), attach("く")),
      Volitional.plain -> Transforms(detach("こう"), attach("く")),
      Alternative.plain -> Transforms(detach("ったり"), attach("く")),
      Imperative.plain -> Transforms(detach("け"), attach("く")),
      Sou.plain -> Transforms(detach("きそう"), attach("く")),
      Tai.plain -> Transforms(detach("きたい"), attach("く")),
      Progressive.plain -> Transforms(detach("っている", "ってる"), attach("く")),
      Form.of(Progressive, Past) -> Transforms(detach("っていた", "ってた"), attach("く")),
      Form.of(Potential, Te) -> Transforms(detach("けて"), attach("く")),
      Form.of(Potential, Past) -> Transforms(detach("けた"), attach("く")),
      Form.of(Causative, Te) -> Transforms(detach("かせて"), attach("く")),
      Form.of(Causative, Past) -> Transforms(detach("かせた"), attach("く")),
      Form.of(Tai, Te) -> Transforms(detach("きたくて"), attach("く")),
      // Polite
      NonPast.polite -> Transforms(detach("きます"), attach("く")),
      Past.polite -> Transforms(detach("きました"), attach("く")),
      Te.polite -> Transforms(detach("きまして"), attach("く")),
      Conditional.polite -> Transforms(detach("きましたら"), attach("く")),
      Provisional.polite -> Transforms(detach("きますなら"), attach("く")),
      Potential.polite -> Transforms(detach("けます"), attach("く")),
      Passive.polite -> Transforms(detach("かれます"), attach("く")),
      Causative.polite -> Transforms(detach("かせます", "かします"), attach("く")),
      CausativePassive.polite -> Transforms(detach("かせられます"), attach("く")),
      Volitional.polite -> Transforms(detach("きましょう"), attach("く")),
      Alternative.polite -> Transforms(detach("きましたり"), attach("く")),
      Imperative.polite -> Transforms(detach("きなさい"), attach("く")),
      Progressive.polite -> Transforms(detach("っています", "ってます"), attach("く")),
      Form.of(Progressive, Past).polite -> Transforms(detach("っていました", "ってました"), attach("く")),
      Form.of(Potential, Te).polite -> Transforms(detach("けまして"), attach("く")),
      Form.of(Potential, Past).polite -> Transforms(detach("けました"), attach("く")),
      Form.of(Causative, Te).polite -> Transforms(detach("かせまして"), attach("く")),
      Form.of(Causative, Past).polite -> Transforms(detach("かせました"), attach("く")),
      // Negative
      NonPast.negative -> Transforms(detach("かない", "かぬ", "かず"), attach("く")),
      Past.negative -> Transforms(detach("かなかった"), attach("く")),
      Te.negative -> Transforms(detach("かなくて", "かないで"), attach("く")),
      Conditional.negative -> Transforms(detach("かなかったら"), attach("く")),
      Provisional.negative -> Transforms(detach("かなければ"), attach("く")),
      Potential.negative -> Transforms(detach("けない"), attach("く")),
      Passive.negative -> Transforms(detach("かれない"), attach("く")),
      Causative.negative -> Transforms(detach("かせない", "かさない"), attach("く")),
      CausativePassive.negative -> Transforms(detach("かせられない"), attach("く")),
      Volitional.negative -> Transforms(detach("くまい"), attach("く")),
      Alternative.negative -> Transforms(detach("かなかったり"), attach("く")),
      Imperative.negative -> Transforms(detach("くな"), attach("く")),
      Sou.negative -> Transforms(detach("かなそう"), attach("く")),
      Form.of(Potential, Sou).negative -> Transforms(detach("けなそう"), attach("く")),
      Tai.negative -> Transforms(detach("きたくない"), attach("く")),
      Progressive.negative -> Transforms(detach("っていない", "ってない"), attach("く")),
      Form.of(Progressive, Past).negative -> Transforms(detach("っていなかった", "ってなかった"), attach("く")),
      Form.of(Tai, Sou).negative -> Transforms(detach("きたくなさそう"), attach("く")),
      Form.of(Potential, Te).negative -> Transforms(detach("けなくて"), attach("く")),
      Form.of(Potential, Past).negative -> Transforms(detach("けなかった"), attach("く")),
      Form.of(Causative, Te).negative -> Transforms(detach("かせなくて"), attach("く")),
      Form.of(Causative, Past).negative -> Transforms(detach("かせなかった"), attach("く")),
      // Polite negative
      NonPast.polite.negative -> Transforms(detach("きません"), attach("く")),
      Past.polite.negative -> Transforms(detach("きませんでした"), attach("く")),
      Te.polite.negative -> Transforms(detach("きませんで"), attach("く")),
      Conditional.polite.negative -> Transforms(detach("きませんでしたら"), attach("く")),
      Provisional.polite.negative -> Transforms(detach("きませんなら"), attach("く")),
      Potential.polite.negative -> Transforms(detach("けません"), attach("く")),
      Passive.polite.negative -> Transforms(detach("かれません"), attach("く")),
      Causative.polite.negative -> Transforms(detach("かせません", "かしません"), attach("く")),
      CausativePassive.polite.negative -> Transforms(detach("かせられません"), attach("く")),
      Volitional.polite.negative -> Transforms(detach("きますまい"), attach("く")),
      Alternative.polite.negative -> Transforms(detach("きませんでしたり"), attach("く")),
      Imperative.polite.negative -> Transforms(detach("きなさるな"), attach("く")),
      Progressive.polite.negative -> Transforms(detach("っていません", "ってません"), attach("く")),
      Form.of(Progressive, Past).polite.negative -> Transforms(detach("っていませんでした", "ってませんでした"), attach("く")),
      Form.of(Potential, Te).polite.negative -> Transforms(detach("けませんでして"), attach("く")),
      Form.of(Potential, Past).polite.negative -> Transforms(detach("けませんでした"), attach("く")),
      Form.of(Causative, Te).polite.negative -> Transforms(detach("かせませんでして"), attach("く")),
      Form.of(Causative, Past).polite.negative -> Transforms(detach("かせませんでした"), attach("く"))
    )
}
