package ject.ja.text.inflection

import ject.ja.text.Form
import ject.ja.text.SubForm.*
import ject.ja.text.Transformation.*
import ject.ja.text.Transforms

object Suru {

  val inflections: Map[Form, Transform] = Map(
    // Plain
    NonPast.plain -> Transforms.identity,
    Past.plain -> Transforms.pure("した"),
    Te.plain -> Transforms.pure("して"),
    Conditional.plain -> Transforms.pure("したら"),
    Provisional.plain -> Transforms.pure("すれば"),
    Potential.plain -> Transforms.pure("できる"),
    Passive.plain -> Transforms.pure("される"),
    Causative.plain -> Transforms.pure("させる", "さす"),
    CausativePassive.plain -> Transforms.pure("させられる"),
    Volitional.plain -> Transforms.pure("しよう"),
    Alternative.plain -> Transforms.pure("したり"),
    Imperative.plain -> Transforms.pure("しろ"),
    Sou.plain -> Transforms.pure("しそう"),
    Tai.plain -> Transforms.pure("したい"),
    Form.of(Past, Potential) -> Transforms.pure("できた"),
    // Polite
    NonPast.polite -> Transforms.pure("します"),
    Past.polite -> Transforms.pure("しました"),
    Te.polite -> Transforms.pure("しまして"),
    Conditional.polite -> Transforms.pure("しましたら"),
    Provisional.polite -> Transforms.pure("しますなら"),
    Potential.polite -> Transforms.pure("できます"),
    Passive.polite -> Transforms.pure("されます"),
    Causative.polite -> Transforms.pure("させます", "さします"),
    CausativePassive.polite -> Transforms.pure("させられます"),
    Volitional.polite -> Transforms.pure("しましょう"),
    Alternative.polite -> Transforms.pure("しましたり"),
    Imperative.polite -> Transforms.pure("しなさい"),
    Form.of(Past, Potential).polite -> Transforms.pure("できました"),
    // Negative
    NonPast.negative -> Transforms.pure("しない", "せぬ", "せず"),
    Past.negative -> Transforms.pure("しなかった"),
    Te.negative -> Transforms.pure("しなくて", "しないで"),
    Conditional.negative -> Transforms.pure("しなかったら"),
    Provisional.negative -> Transforms.pure("しなければ"),
    Potential.negative -> Transforms.pure("できない"),
    Passive.negative -> Transforms.pure("されない"),
    Causative.negative -> Transforms.pure("させない", "ささない"),
    CausativePassive.negative -> Transforms.pure("させられない"),
    Volitional.negative -> Transforms.pure("するまい"),
    Alternative.negative -> Transforms.pure("しなかったり"),
    Imperative.negative -> Transforms.pure("するな"),
    Sou.negative -> Transforms.pure("しなさそう"),
    Form.of(Potential, Sou).negative -> Transforms.pure("できなさそう"),
    Tai.negative -> Transforms.pure("したくない"),
    Form.of(Tai, Sou).negative -> Transforms.pure("したくなさそう"),
    Form.of(Past, Potential).negative -> Transforms.pure("できなかった"),
    // Polite negative
    NonPast.polite.negative -> Transforms.pure("しません"),
    Past.polite.negative -> Transforms.pure("しませんでした"),
    Te.polite.negative -> Transforms.pure("しませんで"),
    Conditional.polite.negative -> Transforms.pure("しませんでしたら"),
    Provisional.polite.negative -> Transforms.pure("しませんなら"),
    Potential.polite.negative -> Transforms.pure("できません"),
    Passive.polite.negative -> Transforms.pure("されません"),
    Causative.polite.negative -> Transforms.pure("させません", "さしません"),
    CausativePassive.polite.negative -> Transforms.pure("させられません"),
    Volitional.polite.negative -> Transforms.pure("しますまい"),
    Alternative.polite.negative -> Transforms.pure("しませんでしたり"),
    Imperative.polite.negative -> Transforms.pure("しなさるな"),
    Form.of(Past, Potential).polite.negative -> Transforms.pure("でませんでした"),
    // Other
    Form.of(Stem) -> Transforms.pure("し")
  )

  val deinflections: Map[Form, Transform] = Map(
    // Plain
    NonPast.plain -> Transforms.identity,
    Past.plain -> Transforms(detach("した"), attach("する")),
    Te.plain -> Transforms(detach("して"), attach("する")),
    Conditional.plain -> Transforms(detach("したら"), attach("する")),
    Provisional.plain -> Transforms(detach("すれば"), attach("する")),
    Potential.plain -> Transforms(detach("できる"), attach("する")),
    Passive.plain -> Transforms(detach("される"), attach("する")),
    Causative.plain -> Transforms(detach("させる", "さす"), attach("する")),
    CausativePassive.plain -> Transforms(detach("させられる"), attach("する")),
    Volitional.plain -> Transforms(detach("しよう"), attach("する")),
    Alternative.plain -> Transforms(detach("したり"), attach("する")),
    Imperative.plain -> Transforms(detach("しろ"), attach("する")),
    Sou.plain -> Transforms(detach("しそう"), attach("する")),
    Tai.plain -> Transforms(detach("したい"), attach("する")),
    Form.of(Past, Potential) -> Transforms(detach("できた"), attach("する")),
    // Polite
    NonPast.polite -> Transforms(detach("します"), attach("する")),
    Past.polite -> Transforms(detach("しました"), attach("する")),
    Te.polite -> Transforms(detach("しまして"), attach("する")),
    Conditional.polite -> Transforms(detach("しましたら"), attach("する")),
    Provisional.polite -> Transforms(detach("しますなら"), attach("する")),
    Potential.polite -> Transforms(detach("できます"), attach("する")),
    Passive.polite -> Transforms(detach("されます"), attach("する")),
    Causative.polite -> Transforms(detach("させます", "さします"), attach("する")),
    CausativePassive.polite -> Transforms(detach("させられます"), attach("する")),
    Volitional.polite -> Transforms(detach("しましょう"), attach("する")),
    Alternative.polite -> Transforms(detach("しましたり"), attach("する")),
    Imperative.polite -> Transforms(detach("しなさい"), attach("する")),
    Form.of(Past, Potential).polite -> Transforms(detach("できました"), attach("する")),
    // Negative
    NonPast.negative -> Transforms(detach("しない", "せぬ", "せず"), attach("する")),
    Past.negative -> Transforms(detach("しなかった"), attach("する")),
    Te.negative -> Transforms(detach("しなくて", "しないで"), attach("する")),
    Conditional.negative -> Transforms(detach("しなかったら"), attach("する")),
    Provisional.negative -> Transforms(detach("しなければ"), attach("する")),
    Potential.negative -> Transforms(detach("できない"), attach("する")),
    Passive.negative -> Transforms(detach("されない"), attach("する")),
    Causative.negative -> Transforms(detach("させない", "ささない"), attach("する")),
    CausativePassive.negative -> Transforms(detach("させられない"), attach("する")),
    Volitional.negative -> Transforms(detach("するまい"), attach("する")),
    Alternative.negative -> Transforms(detach("しなかったり"), attach("する")),
    Imperative.negative -> Transforms(detach("するな"), attach("する")),
    Sou.negative -> Transforms(detach("しなさそう"), attach("する")),
    Form.of(Potential, Sou).negative -> Transforms(detach("できなさそう"), attach("する")),
    Tai.negative -> Transforms(detach("したくない"), attach("する")),
    Form.of(Tai, Sou).negative -> Transforms(detach("したくなさそう"), attach("する")),
    Form.of(Past, Potential).negative -> Transforms(detach("できなかった"), attach("する")),
    // Polite negative
    NonPast.polite.negative -> Transforms(detach("しません"), attach("する")),
    Past.polite.negative -> Transforms(detach("しませんでした"), attach("する")),
    Te.polite.negative -> Transforms(detach("しませんで"), attach("する")),
    Conditional.polite.negative -> Transforms(detach("しませんでしたら"), attach("する")),
    Provisional.polite.negative -> Transforms(detach("しませんなら"), attach("する")),
    Potential.polite.negative -> Transforms(detach("できません"), attach("する")),
    Passive.polite.negative -> Transforms(detach("されません"), attach("する")),
    Causative.polite.negative -> Transforms(detach("させません", "さしません"), attach("する")),
    CausativePassive.polite.negative -> Transforms(detach("させられません"), attach("する")),
    Volitional.polite.negative -> Transforms(detach("しますまい"), attach("する")),
    Alternative.polite.negative -> Transforms(detach("しませんでしたり"), attach("する")),
    Imperative.polite.negative -> Transforms(detach("しなさるな"), attach("する")),
    Form.of(Past, Potential).polite.negative -> Transforms(detach("でませんでした"), attach("する")),
    // Other
    Form.of(Stem) -> Transforms(detach("し"), attach("する"))
  )
}
