addSbtPlugin("org.scalameta"       % "sbt-scalafmt"        % "2.4.2")
addSbtPlugin("com.typesafe.sbt"    % "sbt-native-packager" % "1.7.5")
addSbtPlugin("com.eed3si9n"        % "sbt-assembly"        % "0.15.0")
addSbtPlugin("com.github.reibitto" % "sbt-welcome"         % "0.2.0")
addSbtPlugin("org.scala-js"        % "sbt-scalajs"         % "1.0.1")
addSbtPlugin("ch.epfl.scala"       % "sbt-scalajs-bundler" % "0.17.0")
