addSbtPlugin("org.scalameta"       % "sbt-scalafmt"        % "2.4.6")
addSbtPlugin("com.typesafe.sbt"    % "sbt-native-packager" % "1.8.1")
addSbtPlugin("com.eed3si9n"        % "sbt-assembly"        % "0.15.0")
addSbtPlugin("com.github.reibitto" % "sbt-welcome"         % "0.2.2")
addSbtPlugin("org.scala-js"        % "sbt-scalajs"         % "1.10.1")
addSbtPlugin("ch.epfl.scala"       % "sbt-scalajs-bundler" % "0.20.0")
addSbtPlugin("com.geirsson"        % "sbt-ci-release"      % "1.5.7")

// Scalafix (enable only when needed)
//addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.10.1")
